"""add_allowed_values_to_listing_attribute

Revision ID: 08c6a96e1502
Revises: a7519acf4e00
Create Date: 2026-06-20 15:06:15.761495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '08c6a96e1502'
down_revision = 'a7519acf4e00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_attributes', sa.Column('allowed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_attributes', 'allowed_values')
    # ### end Alembic commands ###
