"""adiciona image_bytes e review_seconds em listing_images

Revision ID: 2f769b55c74e
Revises: c1d5e8b3a207
Create Date: 2026-08-29 18:28:17.165523

"""
from alembic import op
import sqlalchemy as sa


revision = '2f769b55c74e'
down_revision = 'c1d5e8b3a207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_images', sa.Column('image_bytes', sa.LargeBinary(), nullable=True))
    op.add_column('listing_images', sa.Column('review_seconds', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_images', 'review_seconds')
    op.drop_column('listing_images', 'image_bytes')
    # ### end Alembic commands ###
