"""add model to products and sku_model to listings

Revision ID: d3aa35ba6d71
Revises: b8d2f4a6c0e1
Create Date: 2026-06-23 01:20:48.418945

"""
from alembic import op
import sqlalchemy as sa


revision = 'd3aa35ba6d71'
down_revision = 'b8d2f4a6c0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('sku_model', sa.String(length=200), nullable=True))
    op.drop_index('idx_listings_product_id', table_name='listings')
    op.create_index(op.f('ix_listings_product_id'), 'listings', ['product_id'], unique=False)
    op.drop_index('ix_product_images_seller_sku', table_name='product_images')
    op.create_index(op.f('ix_product_images_seller_id'), 'product_images', ['seller_id'], unique=False)
    op.create_index(op.f('ix_product_images_sku'), 'product_images', ['sku'], unique=False)
    op.add_column('products', sa.Column('model', sa.String(length=200), nullable=True))
    op.drop_index('idx_products_seller_id', table_name='products')
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.create_index('idx_products_seller_id', 'products', ['seller_id'], unique=False)
    op.drop_column('products', 'model')
    op.drop_index(op.f('ix_product_images_sku'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_seller_id'), table_name='product_images')
    op.create_index('ix_product_images_seller_sku', 'product_images', ['seller_id', 'sku'], unique=False)
    op.drop_index(op.f('ix_listings_product_id'), table_name='listings')
    op.create_index('idx_listings_product_id', 'listings', ['product_id'], unique=False)
    op.drop_column('listings', 'sku_model')
    # ### end Alembic commands ###
