"""spec014 add failed_step to listings

Revision ID: fbf3f83bf9e4
Revises: 2dc754f932f4
Create Date: 2026-06-26 16:29:59.676048

"""
from alembic import op
import sqlalchemy as sa


revision = 'fbf3f83bf9e4'
down_revision = '2dc754f932f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('failed_step', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'failed_step')
    # ### end Alembic commands ###
